dataconnector:
  athena:
    uri: http://host.docker.internal:8081/api/v1/athena
  mariadb:
    uri: http://host.docker.internal:8081/api/v1/mariadb
  mysql8:
    uri: http://host.docker.internal:8081/api/v1/mysql
  oracle:
    uri: http://host.docker.internal:8081/api/v1/oracle
  snowflake:
    uri: http://host.docker.internal:8081/api/v1/snowflake
