version: "3.8"
services:
  hasura:
    image: hasura/graphql-engine:v2.34.0
    ports:
      - 8080:8080
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_ADMIN_SECRET=myadminsecret
      - HASURA_GRAPHQL_METADATA_DATABASE_URL=postgresql://hasura:hasura@metadata-db:5432/hasura_metadata
    depends_on:
      - hasura-data-connect

  hasura-data-connect:
    image: hasura/graphql-data-connector:v2.32.2
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - metadata-db

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  metadata-db:
    image: postgres:12
    environment:
      - POSTGRES_DB=hasura_metadata
      - POSTGRES_USER=hasura
      - POSTGRES_PASSWORD=hasura
    ports:
      - 5432:5432
# Connect to the mysql database using the following connection string:
# jdbc:mysql://host.docker.internal:3306/db_name?user=username&password=password
